# GitHub Sponsors-enabled usernames
github: [lekhanpro]

# Patreon username
patreon: lekhanpro

# Ko-fi username
ko_fi: lekhanpro

# Buy Me a Coffee username
buy_me_a_coffee: lekhanpro

# Custom sponsorship URL (e.g., PayPal or your personal site)
custom: ['https://paypal.me/lekhanpro']
